# Generated by Django 2.2.4 on 2019-08-15 10:29

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_auto_20190809_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_url',
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('link', 'link'), ('photo', 'photo'), ('video', 'video'), ('animation', 'animation')], default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=core.fields.URLField(blank=True, null=True),
        ),
    ]
