# Generated by Django 2.0.3 on 2018-07-11 19:41

import apps.core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('buttons_type', models.CharField(choices=[('no-buttons', 'No buttons'), ('link', 'Only link'), ('link+comments', 'Link and comments')], default='no-buttons', max_length=100)),
                ('publish_picture', models.BooleanField(default=False)),
                ('linked_title', models.BooleanField(default=False)),
                ('short_link', models.BooleanField(default=False)),
                ('signature', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', apps.core.fields.URLField()),
                ('pic_link', apps.core.fields.URLField(blank=True, null=True)),
                ('comments_link', apps.core.fields.URLField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RssFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('link_field', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.Channel')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='rss.RssFeed'),
        ),
        migrations.AlterUniqueTogether(
            name='rssfeed',
            unique_together={('link', 'channel')},
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('link', 'feed')},
        ),
    ]
