# Generated by Django 2.0.3 on 2018-06-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgur', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgurconfig',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
