# Generated by Django 2.0.3 on 2018-06-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgur', '0002_auto_20180630_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='imgurconfig',
            name='bad_tags',
            field=models.TextField(blank=True, help_text='List of bad tags. Should be separated with comma.'),
        ),
        migrations.AlterField(
            model_name='imgurconfig',
            name='exclude_mode',
            field=models.BooleanField(default=True, help_text='If true then posts with bad tags will be filtered out. Otherwise only posts from with good tags will pass the filter.'),
        ),
        migrations.AlterField(
            model_name='imgurconfig',
            name='good_tags',
            field=models.TextField(blank=True, help_text='List of good tags. Should be separated with comma.'),
        ),
    ]
