# Generated by Django 2.2.4 on 2019-08-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_app', '0002_auto_20190809_0057'),
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subreddits', models.ManyToManyField(related_name='subs', to='reddit.Subreddit')),
                ('telegram_chats', models.ManyToManyField(related_name='subs', to='telegram_app.Chat')),
            ],
        ),
    ]
