# Generated by Django 2.2.4 on 2019-08-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subreddits',
            field=models.ManyToManyField(blank=True, related_name='subs', to='reddit.Subreddit'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='telegram_chats',
            field=models.ManyToManyField(blank=True, related_name='subs', to='telegram_app.Chat'),
        ),
    ]
