# Generated by Django 2.2.4 on 2019-08-10 00:06

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
        ('core', '0002_auto_20190809_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='rss_feeds',
            field=core.models.Related(blank=True, related_name='subs', to='rss.RssFeed'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subreddits',
            field=core.models.Related(blank=True, related_name='subs', to='reddit.Subreddit'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='telegram_chats',
            field=core.models.Related(blank=True, related_name='subs', to='telegram_app.Chat'),
        ),
    ]
