# Generated by Django 2.2.4 on 2019-08-10 15:32

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgur', '0001_initial'),
        ('core', '0003_auto_20190810_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='imgur_configs',
            field=core.models.Related(blank=True, related_name='subs', to='imgur.ImgurConfig'),
        ),
    ]
