# Generated by Django 2.0.3 on 2018-07-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(choices=[('rss', 'RSS App'), ('reddit', 'Reddit App'), ('imgur', 'Imgur App')], max_length=200)),
                ('task', models.CharField(choices=[('publishing', 'Publishing task'), ('deleting', 'Clean up task')], default='publishing', max_length=200)),
                ('note', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(default=0)),
                ('blank', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stats',
                'verbose_name_plural': 'Stats',
            },
        ),
    ]
