# Generated by Django 2.1.5 on 2019-01-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('core', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='type',
            field=models.CharField(
                choices=[('REDDIT', 'Reddit'), ('IMGUR', 'Imgur'), ('RSS', 'RSS')],
                default='REDDIT', max_length=255
            ),
            preserve_default=False,
        )
    ]
