# Generated by Django 2.0.3 on 2018-07-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_stat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
