# Generated by Django 2.2.4 on 2019-08-08 21:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(help_text='Telegram ID.', max_length=255, unique=True)),
                ('username', models.CharField(help_text='Username of telegram ID.', max_length=255)),
                ('type', models.CharField(help_text='Type of chat (eg private, supergroup, etc).', max_length=100)),
                ('title', models.CharField(blank=True, help_text="Group/channel title or user's full name.", max_length=255, null=True)),
                ('forbidden_keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text='List of keywords that are forbidden in current chat.', null=True, size=None)),
            ],
        ),
    ]
