# Generated by Django 2.2.4 on 2019-08-09 00:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='forbidden_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, help_text='List of keywords that are forbidden in current chat.', size=None),
        ),
    ]
