# Generated by Django 2.2.4 on 2019-08-09 16:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_app', '0002_auto_20190809_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='forbidden_keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='List of keywords that are forbidden in current chat.', size=None),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255)),
                ('identifier', models.CharField(help_text='Message ID in specific chat. Similar to message_id but determined before posting and required for filtration.', max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('video_url', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram_app.Chat')),
            ],
            options={
                'unique_together': {('identifier', 'chat')},
            },
        ),
    ]
