# Generated by Django 2.1.5 on 2019-01-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('reddit', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_path',
            field=models.TextField(
                blank=True,
                help_text=(
                    'For posts that need to be temporary saved, such as merged reddit videos.'
                ),
                null=True,
            ),
        )
    ]
