# Generated by Django 2.0.3 on 2018-07-26 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0003_post_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('rejected', 'rejected')], default='accepted', max_length=200),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='low_score_limit',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
