# Generated by Django 2.0.3 on 2018-07-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0005_auto_20180726_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('pending', 'pending'), ('almost', 'almost'), ('rejected', 'rejected')], default='accepted', max_length=200),
        ),
    ]
