# Generated by Django 2.0.3 on 2018-08-07 19:33

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0006_auto_20180729_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=apps.core.fields.URLField(blank=True, null=True),
        ),
    ]
