# Generated by Django 2.0.3 on 2018-06-30 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgurConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_limit', models.IntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0)])),
                ('good_tags', models.TextField(blank=True)),
                ('bad_tags', models.TextField(blank=True)),
                ('exclude_mode', models.BooleanField(default=True, help_text='If true posts with bad tags will be filtered out. Otherwise only posts from with good tags will pass the filter.')),
                ('channel_username', models.CharField(max_length=200, null=True)),
                ('chat_id', models.BigIntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgur_id', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('is_album', models.BooleanField()),
                ('tags', models.TextField()),
                ('images_links', models.TextField()),
            ],
        ),
    ]
