# Generated by Django 2.2.4 on 2019-08-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgurconfig',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
