# Generated by Django 2.2.4 on 2019-08-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgur', '0002_imgurconfig_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
