# Generated by Django 2.1.5 on 2019-01-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [('core', '0002_subscription_type')]

    operations = [
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'username',
                    models.CharField(
                        blank=True,
                        help_text='Channel username, should start with @.',
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    'chat_id',
                    models.BigIntegerField(
                        blank=True,
                        help_text=(
                            'Telegram chat id of channel, '
                            'can be omitted if username is specified.'
                        ),
                        null=True,
                    ),
                ),
                ('uuid', models.UUIDField()),
                (
                    'subscriptions',
                    models.ManyToManyField(
                        blank=True,
                        help_text='List of channel subscriptions.',
                        related_name='tg_channels',
                        to='core.Subscription',
                    ),
                ),
            ],
        )
    ]
