# Generated by Django 2.1.5 on 2019-01-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [('core', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('chat_id', models.BigIntegerField(blank=True, null=True)),
                (
                    'subscriptions',
                    models.ManyToManyField(
                        related_name='tg_channels', to='core.Subscription', blank=True
                    ),
                ),
            ],
        )
    ]
