# Generated by Django 2.1.5 on 2019-01-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchannel',
            name='name',
            field=models.TextField(blank=True, help_text='Human friendly name of channel.', null=True),
        ),
        migrations.AlterField(
            model_name='telegramchannel',
            name='chat_id',
            field=models.CharField(blank=True, help_text='Telegram chat id of channel, can be omitted if username is specified.', max_length=255, null=True),
        ),
    ]
